
import { PasaranData } from './types';

export const PASARAN_SCHEDULE: PasaranData[] = [
  { id: '1', name: 'HOKI DRAW', betClose: '00:00 WIB', open: '00:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '2', name: 'TOTO MACAU PAGI', betClose: '00:00 WIB', open: '00:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.poolstotomacao.com/', initialDone: true },
  { id: '3', name: 'HUAHIN0100', betClose: '00:45 WIB', open: '01:00 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://huahinlottery.com/', initialDone: true },
  { id: '4', name: 'HOKI DRAW', betClose: '01:00 WIB', open: '01:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '5', name: 'KENTUCKY MIDDAY', betClose: '01:05 WIB', open: '01:20 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.kylottery.com/apps/draw_games/pick4/index.html', initialDone: true },
  { id: '6', name: 'FLORIDA MIDDAY', betClose: '01:20 WIB', open: '01:30 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://floridalottery.com/games/draw-games/pick-4', initialDone: true },
  { id: '7', name: 'BANGKOK 0130', betClose: '01:15 WIB', open: '01:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://bangkokpoolstoday.com/', initialDone: true },
  { id: '8', name: 'HOKI DRAW', betClose: '02:00 WIB', open: '02:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '9', name: 'NEW YORK MIDDAY', betClose: '02:15 WIB', open: '02:25 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://nylottery.ny.gov/draw-game?game=win4', initialDone: true },
  { id: '10', name: 'BRUNEI02', betClose: '02:30 WIB', open: '02:43 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://bruneipools.com/', initialDone: true },
  { id: '11', name: 'CAROLINA DAY', betClose: '02:45 WIB', open: '03:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.wral.com/video/daytime-pick-3-and-pick-4-streaming/2570000/', initialDone: true },
  { id: '12', name: 'HOKI DRAW', betClose: '03:00 WIB', open: '03:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '13', name: 'OREGON 03', betClose: '04:00 WIB', open: '04:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.oregonlottery.org/pick-4/winning-numbers/', initialDone: true },
  { id: '14', name: 'HOKI DRAW', betClose: '04:00 WIB', open: '04:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '15', name: 'HOKI DRAW', betClose: '05:00 WIB', open: '05:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '16', name: 'HOKI DRAW', betClose: '06:00 WIB', open: '06:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '17', name: 'OREGON 06', betClose: '07:00 WIB', open: '07:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.oregonlottery.org/pick-4/winning-numbers/', initialDone: true },
  { id: '18', name: 'HOKI DRAW', betClose: '07:00 WIB', open: '07:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '19', name: 'HOKI DRAW', betClose: '08:00 WIB', open: '08:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '20', name: 'HOKI DRAW', betClose: '09:00 WIB', open: '09:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '21', name: 'BANGKOK 0930', betClose: '09:15 WIB', open: '09:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://bangkokpoolstoday.com/', initialDone: true },
  { id: '22', name: 'CALIFORNIA', betClose: '09:25 WIB', open: '09:40 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.calottery.com/draw-games/daily-4', initialDone: true },
  { id: '23', name: 'FLORIDA EVENING', betClose: '09:35 WIB', open: '09:45 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://floridalottery.com/games/draw-games/pick-4', initialDone: true },
  { id: '24', name: 'OREGON 09', betClose: '09:50 WIB', open: '10:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.oregonlottery.org/pick-4/winning-numbers/', initialDone: true },
  { id: '25', name: 'HOKI DRAW', betClose: '10:00 WIB', open: '10:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '26', name: 'NEW YORK EVENING', betClose: '10:25 WIB', open: '10:35 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://nylottery.ny.gov/draw-game?game=win4', initialDone: true },
  { id: '27', name: 'TOTO CAMBODIA LIVE', betClose: '10:45 WIB', open: '11:00 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://totocambodialive.com/live-draw.html', initialDone: true },
  { id: '28', name: 'KENTUCKY EVENING', betClose: '10:45 WIB', open: '11:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.kylottery.com/apps/draw_games/pick4/index.html', initialDone: true },
  { id: '29', name: 'HOKI DRAW', betClose: '11:00 WIB', open: '11:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '30', name: 'CHELSEA11', betClose: '11:00 WIB', open: '11:15 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://chelseapools.co.uk/', initialDone: true },
  { id: '31', name: 'CAROLINA EVENING', betClose: '11:17 WIB', open: '11:22 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.wral.com/evening-pick-3-pick-4-and-cash-5/1075494/', initialDone: true },
  { id: '32', name: 'HOKI DRAW', betClose: '12:00 WIB', open: '12:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: true },
  { id: '33', name: 'BULLSEYE', betClose: '12:00 WIB', open: '12:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://mylotto.co.nz/results/bullseye', initialDone: true },
  { id: '34', name: 'POIPET12', betClose: '12:15 WIB', open: '12:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://poipetlottery.com/', initialDone: false },
  { id: '35', name: 'OREGON 12', betClose: '12:50 WIB', open: '13:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.oregonlottery.org/pick-4/winning-numbers/', initialDone: false },
  { id: '36', name: 'HOKI DRAW', betClose: '13:00 WIB', open: '13:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '37', name: 'TOTO MACAU SIANG', betClose: '13:00 WIB', open: '13:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.poolstotomacao.com/', initialDone: false },
  { id: '38', name: 'SYDNEY LOTTO', betClose: '13:49 WIB', open: '13:50 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://lottosydney.fun/', initialDone: false },
  { id: '39', name: 'HOKI DRAW', betClose: '14:00 WIB', open: '14:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '40', name: 'BRUNEI14', betClose: '14:30 WIB', open: '14:45 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://bruneipools.com/', initialDone: false },
  { id: '41', name: 'HOKI DRAW', betClose: '15:00 WIB', open: '15:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '42', name: 'CHELSEA15', betClose: '15:00 WIB', open: '15:15 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://chelseapools.co.uk/', initialDone: false },
  { id: '43', name: 'POIPET15', betClose: '15:15 WIB', open: '15:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://poipetlottery.com/', initialDone: false },
  { id: '44', name: 'TOTOMALI1530', betClose: '15:15 WIB', open: '15:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://totomali.com/', initialDone: false },
  { id: '45', name: 'HOKI DRAW', betClose: '16:00 WIB', open: '16:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '46', name: 'TOTO MACAU SORE', betClose: '16:00 WIB', open: '16:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.poolstotomacao.com/', initialDone: false },
  { id: '47', name: 'HUAHIN1630', betClose: '16:15 WIB', open: '16:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://huahinlottery.com/', initialDone: false },
  { id: '48', name: 'KING KONG4D SORE', betClose: '17:00 WIB', open: '17:01 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://kingkongpools.id', initialDone: false },
  { id: '51', name: 'HOKI DRAW', betClose: '17:00 WIB', open: '17:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '52', name: 'SINGAPORE', betClose: '17:30 WIB', open: '17:45 WIB', status: 'Open', prize: 'SG PRIZE', liveDraw: 'ADA LIVE', link: 'https://online.singaporepools.com/en/lottery', initialDone: false },
  { id: '53', name: 'HOKI DRAW', betClose: '18:00 WIB', open: '18:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '54', name: 'MAGNUM4D', betClose: '18:10 WIB', open: '18:40 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.magnum4d.my/en', initialDone: false },
  { id: '55', name: 'HOKI DRAW', betClose: '19:00 WIB', open: '19:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '56', name: 'TOTO MACAU MALAM 1', betClose: '19:00 WIB', open: '19:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.poolstotomacao.com/', initialDone: false },
  { id: '57', name: 'CHELSEA19', betClose: '19:00 WIB', open: '19:15 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://chelseapools.co.uk/', initialDone: false },
  { id: '58', name: 'POIPET19', betClose: '19:30 WIB', open: '19:45 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://poipetlottery.com/', initialDone: false },
  { id: '59', name: 'PCSO', betClose: '19:30 WIB', open: '19:45 WIB', status: 'Open', prize: 'PHP PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.pcso.gov.ph/', initialDone: false },
  { id: '60', name: 'HOKI DRAW', betClose: '20:00 WIB', open: '20:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '61', name: 'TOTOMALI2030', betClose: '20:15 WIB', open: '20:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://totomali.com/', initialDone: false },
  { id: '62', name: 'HOKI DRAW', betClose: '21:00 WIB', open: '21:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '63', name: 'HUAHIN2100', betClose: '20:45 WIB', open: '21:00 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://huahinlottery.com/', initialDone: false },
  { id: '64', name: 'CHELSEA21', betClose: '21:00 WIB', open: '21:15 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://chelseapools.co.uk/', initialDone: false },
  { id: '65', name: 'NEVADA', betClose: '21:15 WIB', open: '21:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://www.nevadalottery.us/', initialDone: false },
  { id: '66', name: 'BRUNEI21', betClose: '21:30 WIB', open: '21:45 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'TIDAK ADA', link: 'https://bruneipools.com/', initialDone: false },
  { id: '67', name: 'HOKI DRAW', betClose: '22:00 WIB', open: '22:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '68', name: 'TOTO MACAU MALAM 2', betClose: '22:00 WIB', open: '22:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.poolstotomacao.com/', initialDone: false },
  { id: '69', name: 'POIPET22', betClose: '22:30 WIB', open: '22:45 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://poipetlottery.com/', initialDone: false },
  { id: '70', name: 'HOKI DRAW', betClose: '23:00 WIB', open: '23:00 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://Hokidraw.com', initialDone: false },
  { id: '71', name: 'HONGKONG LOTTO', betClose: '23:00 WIB', open: '23:15 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'http://hongkongfunlotto.net', initialDone: false },
  { id: '72', name: 'TOTO MACAU MALAM 3', betClose: '23:00 WIB', open: '23:15 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'https://www.poolstotomacao.com/', initialDone: false },
  { id: '73', name: 'TOTOMALI2330', betClose: '23:15 WIB', open: '23:30 WIB', status: 'Open', prize: '3 PRIZE', liveDraw: 'ADA LIVE', link: 'https://totomali.com/', initialDone: false },
  { id: '74', name: 'KING KONG4D MALAM', betClose: '23:30 WIB', open: '23:31 WIB', status: 'Open', prize: '1 PRIZE', liveDraw: 'ADA LIVE', link: 'http://kingkongpools.id', initialDone: false },
];

export const SYAIR_SENTENCES = [
  "Bintang kejora bersinar terang di ufuk timur.",
  "Naga bersembunyi di balik awan mendung.",
  "Angka sakti muncul di tengah malam buta.",
  "Kunci keberuntungan ada pada kesabaran.",
  "Mimpi semalam adalah petunjuk hari ini.",
  "Gunung tinggi menyimpan harta yang tak terduga.",
  "Langkah kaki macan tak bersuara di hutan jati.",
  "Air mengalir tenang membawa berkah melimpah.",
  "Hati-hati dengan bisikan angin sore.",
  "Cahaya bulan purnama menerangi jalan yang gelap.",
  "Rejeki nomplok datang tanpa diduga-duga.",
  "Siapkan wadah besar untuk menampung emas.",
];

export const BANK_PREFIXES: Record<string, string> = {
  '123': 'Bank Mandiri',
  '456': 'Bank Central Asia (BCA)',
  '789': 'Bank Rakyat Indonesia (BRI)',
  '002': 'Bank BNI',
  '014': 'Bank Danamon',
  '016': 'Bank Permata',
  '022': 'Bank CIMB Niaga',
};

// Shio Zodiac Base (Standard Order)
export const ZODIAC_ANIMALS = [
  "TIKUS", "KERBAU", "MACAN", "KELINCI", "NAGA", "ULAR", 
  "KUDA", "KAMBING", "MONYET", "AYAM", "ANJING", "BABI"
];

// Chinese New Year Dates (Lunar New Year) for Auto-Shift
export const LUNAR_NEW_YEARS = [
  { year: 2024, date: "2024-02-10", animal: "NAGA" },
  { year: 2025, date: "2025-01-29", animal: "ULAR" },
  { year: 2026, date: "2026-02-17", animal: "KUDA" },
  { year: 2027, date: "2027-02-06", animal: "KAMBING" },
  { year: 2028, date: "2028-01-26", animal: "MONYET" },
];
