
import React, { useState } from 'react';
import { Copy, RefreshCw, ExternalLink, Trash2, Palette, FileCode } from 'lucide-react';

interface Props {
  showToast: (message: string, type?: 'success' | 'error') => void;
}

interface ColorTheme {
  name: string;
  primary: string;
  secondary: string;
  glow: string;
}

const COLOR_THEMES: ColorTheme[] = [
  { name: 'Classic Blue', primary: '#003366', secondary: '#66ccff', glow: '#0099ff' },
  { name: 'Luxury Gold', primary: '#856d11', secondary: '#f5da6c', glow: '#ffd700' },
  { name: 'Cyber Red', primary: '#8b0000', secondary: '#ff4d4d', glow: '#ff0000' },
  { name: 'Deep Emerald', primary: '#004d40', secondary: '#1de9b6', glow: '#00ff88' },
  { name: 'Royal Purple', primary: '#4b0082', secondary: '#da70d6', glow: '#bc13fe' },
  { name: 'Sunset Orange', primary: '#e65100', secondary: '#ffb74d', glow: '#ff8c00' },
  { name: 'Electric Pink', primary: '#880e4f', secondary: '#f06292', glow: '#ff1493' },
  { name: 'Midnight Blue', primary: '#1a237e', secondary: '#7986cb', glow: '#3f51b5' },
  { name: 'Toxic Green', primary: '#1b5e20', secondary: '#8bc34a', glow: '#44ff00' },
  { name: 'Carbon Silver', primary: '#37474f', secondary: '#cfd8dc', glow: '#ffffff' },
  { name: 'Ocean Cyan', primary: '#006064', secondary: '#4dd0e1', glow: '#00e5ff' },
  { name: 'Blood Dark', primary: '#4a0e0e', secondary: '#f44336', glow: '#ff4444' },
];

interface MatchData {
  league: string;
  matches: {
    date: string;
    time: string;
    teams: string;
    score: string;
  }[];
}

const FootballPrediction: React.FC<Props> = ({ showToast }) => {
  const [inputText, setInputText] = useState('');
  const [selectedTheme, setSelectedTheme] = useState(COLOR_THEMES[0]);
  const [generatedHTML, setGeneratedHTML] = useState('');

  const parseInput = (text: string): MatchData[] => {
    const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    const data: MatchData[] = [];
    let currentLeague = '';

    lines.forEach(line => {
      // Deteksi Liga (Biasanya huruf besar semua atau tidak mengandung jam/skor)
      const isMatchLine = line.match(/\d{2}\/\d{2}\s\d{2}:\d{2}/);
      
      if (!isMatchLine) {
        currentLeague = line.toUpperCase();
      } else {
        const match = line.match(/(\d{2}\/\d{2})\s(\d{2}:\d{2})\sWIB\s(.+?)\s(\d+\s:\s\d+)/);
        if (match && currentLeague) {
          const [_, date, time, teams, score] = match;
          let leagueGroup = data.find(d => d.league === currentLeague);
          if (!leagueGroup) {
            leagueGroup = { league: currentLeague, matches: [] };
            data.push(leagueGroup);
          }
          leagueGroup.matches.push({ date, time: time + ' WIB', teams, score });
        }
      }
    });

    return data;
  };

  const generateScript = () => {
    if (!inputText.trim()) {
      showToast('Masukkan data prediksi terlebih dahulu', 'error');
      return;
    }

    const parsedData = parseInput(inputText);
    if (parsedData.length === 0) {
      showToast('Format teks tidak valid', 'error');
      return;
    }

    const theme = selectedTheme;
    
    let tableRows = '';
    parsedData.forEach(group => {
      tableRows += `
<tr>
  <td colspan="3" class="league">⚽ ${group.league}</td>
</tr>
<tr>
  <th>TANGGAL</th>
  <th>PERTANDINGAN</th>
  <th>PREDIKSI</th>
</tr>`;
      group.matches.forEach(m => {
        tableRows += `
<tr>
  <td>${m.date}<br /><span>${m.time}</span></td>
  <td>${m.teams}</td>
  <td>${m.score}</td>
</tr>`;
      });
      tableRows += `<tr><td colspan="3" style="height: 15px;"></td></tr>`;
    });

    const fullHTML = `<!-- KODE GENERATED BY ABADiVIN - Prediksi Bola -->
<style>
body {
  background: url("https://cdn.areabermain.club/assets/cdn/az2/2026/01/17/20260117/fd23ec7444085ce9baaec2e5ef286006/abadiwin-background.jpg") center/cover fixed no-repeat;
  margin:0;
  font-family: Arial, sans-serif;
  color:#fff;
}
.arena-wrap {
  background: rgba(0,0,0,0.88);
  padding: 20px;
  border-radius: 12px;
  box-shadow: 0 0 35px ${theme.glow}b3;
  animation: fadeIn 1.5s ease;
  max-width: 1000px;
  margin: auto;
}
@keyframes fadeIn { from {opacity:0;} to {opacity:1;} }
.logo { text-align:center; margin-bottom:15px; }
.logo img { max-width:260px; filter: drop-shadow(0 0 20px ${theme.glow}); animation: glow 2s infinite alternate; }
@keyframes glow { from {filter: drop-shadow(0 0 10px ${theme.secondary});} to {filter: drop-shadow(0 0 30px #ffffff);} }
.marquee {
  background: linear-gradient(90deg,${theme.primary},${theme.secondary},${theme.primary});
  color:#fff;
  padding:12px;
  overflow:hidden;
  white-space:nowrap;
  font-weight:bold;
  margin-bottom:15px;
  border-radius: 8px;
  box-shadow: 0 0 10px ${theme.glow};
}
.marquee span { display:inline-block; animation: run 25s linear infinite; }
@keyframes run { 0%{transform:translateX(100%)} 100%{transform:translateX(-100%)} }
table {
  width: 100%;
  border-collapse: collapse;
  background: rgba(30,30,30,0.9);
  box-shadow: 0 0 20px ${theme.glow}b3;
  font-size: 14px;
  margin-bottom: 20px;
  border-radius: 8px;
  overflow: hidden;
}
th {
  background: linear-gradient(135deg,${theme.primary},${theme.secondary});
  color: #fff;
  text-align: center;
  padding: 10px;
  font-weight: bold;
  text-transform: uppercase;
  border-bottom: 2px solid ${theme.secondary};
  text-shadow: 0 0 6px #000;
}
td {
  padding: 8px 10px;
  border-bottom: 1px solid ${theme.primary};
  color:#cceeff;
  text-align: center;
  word-break: break-word;
  transition: 0.3s;
}
td span { font-size: 12px; color: ${theme.secondary}; }
tr:hover td { background: ${theme.primary}b3; color:#fff; font-weight:bold; transform: scale(1.02); }
.league {
  background: linear-gradient(135deg,${theme.primary},${theme.glow});
  color:#cceeff;
  font-weight:bold;
  text-align:center;
  padding:14px;
  font-size:17px;
  letter-spacing:1px;
  text-shadow: 0 0 10px ${theme.glow};
  border-radius: 8px 8px 0 0;
}
@media only screen and (max-width: 420px) {
  table { font-size: 11px; border-radius:6px; }
  td span { font-size: 10px; }
  th { padding: 6px 4px; font-size: 12px; }
  .league { font-size: 16px; padding: 10px 5px; }
}
</style>
<div class="arena-wrap" id="resultArea">
<div class="logo"><img src="https://cdn.areabermain.club/assets/cdn/az2/2026/01/17/20260117/906884f06ce7e9d84c4fb76480da1e49/abadiwin-logoacc.png" /></div>
<div class="marquee"><span>🔥 Prediksi Bola Terupdate &bull; Analisis Akurat &bull; ABADIWIN 🔥</span></div>
<table id="tabel">
<tbody>
${tableRows}
</tbody>
</table>
</div>`.trim();

    setGeneratedHTML(fullHTML);
    showToast('Script berhasil dibuat!', 'success');
  };

  const copyResult = () => {
    navigator.clipboard.writeText(generatedHTML);
    showToast('Script disalin ke clipboard!', 'success');
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header & Quick Links */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h3 className="text-2xl font-black font-orbitron text-white uppercase tracking-tighter">Football Script Generator</h3>
          <p className="text-[10px] text-zinc-500 uppercase font-bold tracking-[0.3em]">Advanced Layout Engine V3</p>
        </div>
        <div className="flex gap-2">
          <a href="https://shortq.net/PREDIKSIBOLA" target="_blank" rel="noreferrer" className="px-4 py-2 bg-blue-600/20 border border-blue-500/30 rounded-xl text-[10px] font-black text-blue-400 flex items-center hover:bg-blue-600/40 transition-all uppercase">
            Source 1 <ExternalLink className="w-3 h-3 ml-2" />
          </a>
          <a href="https://kembarprediksi.online/category/prediksi-bola/" target="_blank" rel="noreferrer" className="px-4 py-2 bg-emerald-600/20 border border-emerald-500/30 rounded-xl text-[10px] font-black text-emerald-400 flex items-center hover:bg-emerald-600/40 transition-all uppercase">
            Source 2 <ExternalLink className="w-3 h-3 ml-2" />
          </a>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Left Panel: Input & Settings */}
        <div className="space-y-6">
          <div className="glass-panel p-6 rounded-[30px] border border-white/5 space-y-6">
            <div className="flex items-center justify-between">
              <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest flex items-center">
                <Palette className="w-4 h-4 mr-2 text-[var(--primary-color)]" /> Select Color Style
              </label>
              <span className="text-[9px] font-bold text-zinc-600">{selectedTheme.name}</span>
            </div>
            <div className="grid grid-cols-6 gap-2">
              {COLOR_THEMES.map((theme) => (
                <button
                  key={theme.name}
                  onClick={() => setSelectedTheme(theme)}
                  title={theme.name}
                  className={`h-10 rounded-xl transition-all border-2 ${selectedTheme.name === theme.name ? 'border-white scale-110 shadow-lg' : 'border-transparent opacity-60 hover:opacity-100'}`}
                  style={{ background: `linear-gradient(135deg, ${theme.primary}, ${theme.secondary})` }}
                />
              ))}
            </div>

            <div className="space-y-2 pt-4">
              <div className="flex justify-between items-center">
                <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">Input Raw Match Data</label>
                <button onClick={() => setInputText('')} className="text-zinc-600 hover:text-rose-500 transition-colors">
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder="Paste data di sini...&#10;Contoh:&#10;ITALY SERIE A&#10;14/02 02:45 WIB Pisa VS AC Milan 1 : 2"
                className="w-full h-64 bg-black/60 border border-white/10 rounded-2xl p-5 font-mono text-xs text-zinc-300 outline-none focus:border-[var(--primary-color)] transition-all custom-scrollbar"
              />
            </div>

            <button
              onClick={generateScript}
              className="w-full bg-[var(--primary-color)] text-black font-black font-orbitron py-5 rounded-2xl text-sm flex items-center justify-center hover:opacity-80 transition-all shadow-[0_0_20px_rgba(0,255,0,0.2)]"
            >
              <RefreshCw className="w-5 h-5 mr-3" /> GENERATE HTML SCRIPT
            </button>
          </div>
        </div>

        {/* Right Panel: Output Preview */}
        <div className="space-y-4">
          <div className="flex justify-between items-center px-4">
            <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest flex items-center">
              <FileCode className="w-4 h-4 mr-2 text-blue-400" /> HTML Code Output
            </label>
            {generatedHTML && (
              <button onClick={copyResult} className="text-[10px] font-black text-blue-400 uppercase flex items-center hover:opacity-70 transition-all">
                <Copy className="w-3.5 h-3.5 mr-2" /> Copy Script
              </button>
            )}
          </div>
          <div className="glass-panel p-6 rounded-[30px] border border-white/5 h-[620px] flex flex-col">
            {generatedHTML ? (
              <pre className="flex-1 text-[11px] font-mono text-zinc-400 overflow-auto custom-scrollbar whitespace-pre-wrap select-all">
                {generatedHTML}
              </pre>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-zinc-700 space-y-4 opacity-30">
                <FileCode className="w-16 h-16" />
                <p className="font-orbitron font-black text-xs uppercase tracking-widest text-center">
                  Configure and generate<br/>to produce script code
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default FootballPrediction;
